// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jointsposition.proto

#ifndef PROTOBUF_jointsposition_2eproto__INCLUDED
#define PROTOBUF_jointsposition_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace QRsensor {
namespace msgs {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_jointsposition_2eproto();
void protobuf_AssignDesc_jointsposition_2eproto();
void protobuf_ShutdownFile_jointsposition_2eproto();

class JointsPosition;
class LimbJoints;

// ===================================================================

class LimbJoints : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:QRsensor.msgs.LimbJoints) */ {
 public:
  LimbJoints();
  virtual ~LimbJoints();

  LimbJoints(const LimbJoints& from);

  inline LimbJoints& operator=(const LimbJoints& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LimbJoints& default_instance();

  void Swap(LimbJoints* other);

  // implements Message ----------------------------------------------

  inline LimbJoints* New() const { return New(NULL); }

  LimbJoints* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LimbJoints& from);
  void MergeFrom(const LimbJoints& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LimbJoints* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double theta1 = 1;
  void clear_theta1();
  static const int kTheta1FieldNumber = 1;
  double theta1() const;
  void set_theta1(double value);

  // optional double theta2 = 2;
  void clear_theta2();
  static const int kTheta2FieldNumber = 2;
  double theta2() const;
  void set_theta2(double value);

  // optional double theta3 = 3;
  void clear_theta3();
  static const int kTheta3FieldNumber = 3;
  double theta3() const;
  void set_theta3(double value);

  // @@protoc_insertion_point(class_scope:QRsensor.msgs.LimbJoints)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double theta1_;
  double theta2_;
  double theta3_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_jointsposition_2eproto();
  friend void protobuf_AssignDesc_jointsposition_2eproto();
  friend void protobuf_ShutdownFile_jointsposition_2eproto();

  void InitAsDefaultInstance();
  static LimbJoints* default_instance_;
};
// -------------------------------------------------------------------

class JointsPosition : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:QRsensor.msgs.JointsPosition) */ {
 public:
  JointsPosition();
  virtual ~JointsPosition();

  JointsPosition(const JointsPosition& from);

  inline JointsPosition& operator=(const JointsPosition& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const JointsPosition& default_instance();

  void Swap(JointsPosition* other);

  // implements Message ----------------------------------------------

  inline JointsPosition* New() const { return New(NULL); }

  JointsPosition* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const JointsPosition& from);
  void MergeFrom(const JointsPosition& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(JointsPosition* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .QRsensor.msgs.LimbJoints limbjoints = 1;
  int limbjoints_size() const;
  void clear_limbjoints();
  static const int kLimbjointsFieldNumber = 1;
  const ::QRsensor::msgs::LimbJoints& limbjoints(int index) const;
  ::QRsensor::msgs::LimbJoints* mutable_limbjoints(int index);
  ::QRsensor::msgs::LimbJoints* add_limbjoints();
  ::google::protobuf::RepeatedPtrField< ::QRsensor::msgs::LimbJoints >*
      mutable_limbjoints();
  const ::google::protobuf::RepeatedPtrField< ::QRsensor::msgs::LimbJoints >&
      limbjoints() const;

  // @@protoc_insertion_point(class_scope:QRsensor.msgs.JointsPosition)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::QRsensor::msgs::LimbJoints > limbjoints_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_jointsposition_2eproto();
  friend void protobuf_AssignDesc_jointsposition_2eproto();
  friend void protobuf_ShutdownFile_jointsposition_2eproto();

  void InitAsDefaultInstance();
  static JointsPosition* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// LimbJoints

// optional double theta1 = 1;
inline void LimbJoints::clear_theta1() {
  theta1_ = 0;
}
inline double LimbJoints::theta1() const {
  // @@protoc_insertion_point(field_get:QRsensor.msgs.LimbJoints.theta1)
  return theta1_;
}
inline void LimbJoints::set_theta1(double value) {
  
  theta1_ = value;
  // @@protoc_insertion_point(field_set:QRsensor.msgs.LimbJoints.theta1)
}

// optional double theta2 = 2;
inline void LimbJoints::clear_theta2() {
  theta2_ = 0;
}
inline double LimbJoints::theta2() const {
  // @@protoc_insertion_point(field_get:QRsensor.msgs.LimbJoints.theta2)
  return theta2_;
}
inline void LimbJoints::set_theta2(double value) {
  
  theta2_ = value;
  // @@protoc_insertion_point(field_set:QRsensor.msgs.LimbJoints.theta2)
}

// optional double theta3 = 3;
inline void LimbJoints::clear_theta3() {
  theta3_ = 0;
}
inline double LimbJoints::theta3() const {
  // @@protoc_insertion_point(field_get:QRsensor.msgs.LimbJoints.theta3)
  return theta3_;
}
inline void LimbJoints::set_theta3(double value) {
  
  theta3_ = value;
  // @@protoc_insertion_point(field_set:QRsensor.msgs.LimbJoints.theta3)
}

// -------------------------------------------------------------------

// JointsPosition

// repeated .QRsensor.msgs.LimbJoints limbjoints = 1;
inline int JointsPosition::limbjoints_size() const {
  return limbjoints_.size();
}
inline void JointsPosition::clear_limbjoints() {
  limbjoints_.Clear();
}
inline const ::QRsensor::msgs::LimbJoints& JointsPosition::limbjoints(int index) const {
  // @@protoc_insertion_point(field_get:QRsensor.msgs.JointsPosition.limbjoints)
  return limbjoints_.Get(index);
}
inline ::QRsensor::msgs::LimbJoints* JointsPosition::mutable_limbjoints(int index) {
  // @@protoc_insertion_point(field_mutable:QRsensor.msgs.JointsPosition.limbjoints)
  return limbjoints_.Mutable(index);
}
inline ::QRsensor::msgs::LimbJoints* JointsPosition::add_limbjoints() {
  // @@protoc_insertion_point(field_add:QRsensor.msgs.JointsPosition.limbjoints)
  return limbjoints_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::QRsensor::msgs::LimbJoints >*
JointsPosition::mutable_limbjoints() {
  // @@protoc_insertion_point(field_mutable_list:QRsensor.msgs.JointsPosition.limbjoints)
  return &limbjoints_;
}
inline const ::google::protobuf::RepeatedPtrField< ::QRsensor::msgs::LimbJoints >&
JointsPosition::limbjoints() const {
  // @@protoc_insertion_point(field_list:QRsensor.msgs.JointsPosition.limbjoints)
  return limbjoints_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace QRsensor

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_jointsposition_2eproto__INCLUDED
